version: "3"
services:
  app:
    build: .
    networks:
      - default
    volumes:
      - ./app:/app
    entrypoint: ["bash", "-c", "tail -f /dev/null"]

  db:
    image: mongo:latest
    networks:
      default:
        aliases:
          - mongohost

    ports:
      - "${MONGO_PORT_FORWARD:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - mongo_data:/data/db

networks:
  default:

volumes:
  mongo_data: